/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escuela;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author ellia
 */
public class Agregar_alumno extends javax.swing.JFrame {

    String num;

    /**
     * Creates new form Agregar_alumno
     */
    public Agregar_alumno() {
        initComponents();
        setLocationRelativeTo(null);
        this.mausqueHerramienta.setVisible(false);//esto me sirve para esconder un dato que tengo que utilizar, pero que el usuario no debe ver
        this.numAlumnos.setVisible(false);//esto me sirve para esconder un dato que tengo que utilizar, pero que el usuario no debe ver

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/escuela", "root", "Ivansito07615.");
            PreparedStatement pst = cn.prepareStatement("select Grado from grado");
            ResultSet rs = pst.executeQuery();
            grado.addItem("Grado");
            while (rs.next()) {
                grado.addItem(rs.getString("Grado"));
            }
        } catch (SQLException E) {
            System.out.println(E);
            JOptionPane.showMessageDialog(rootPane, "Algo ha Ocurrido con la conexion", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/escuela", "root", "Ivansito07615.");
            PreparedStatement pst = cn.prepareStatement("select Seccion from seccion");
            ResultSet rs = pst.executeQuery();
            seccion.addItem("Seccion");
            while (rs.next()) {
                seccion.addItem(rs.getString("Seccion"));
            }
        } catch (SQLException E) {
            System.out.println(E);
            JOptionPane.showMessageDialog(rootPane, "Algo ha Ocurrido con la conexion", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/escuela", "root", "Ivansito07615.");
            PreparedStatement pst = cn.prepareStatement("select Nombre from rolalumno");
            ResultSet rs = pst.executeQuery();
            rol.addItem("Rol");
            while (rs.next()) {
                rol.addItem(rs.getString("Nombre"));
            }
        } catch (SQLException E) {
            System.out.println(E);
            JOptionPane.showMessageDialog(rootPane, "Algo ha Ocurrido con la conexion", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/escuela", "root", "Ivansito07615.");
            PreparedStatement pst = cn.prepareStatement("select IDAula from aula");
            ResultSet rs = pst.executeQuery();
            aula.addItem("Aula");
            while (rs.next()) {
                aula.addItem(rs.getString("IDAula"));
            }
        } catch (SQLException E) {
            System.out.println(E);
            JOptionPane.showMessageDialog(rootPane, "Algo ha Ocurrido con la conexion", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        matricula = new javax.swing.JTextField();
        grado = new javax.swing.JComboBox<>();
        seccion = new javax.swing.JComboBox<>();
        rol = new javax.swing.JComboBox<>();
        agregar_estudiante = new javax.swing.JButton();
        aula = new javax.swing.JComboBox<>();
        numAlumnos = new javax.swing.JLabel();
        mausqueHerramienta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGREGAR ALUMNO");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Dirección");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Matrícula");

        grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoActionPerformed(evt);
            }
        });

        agregar_estudiante.setText("AGREGAR");
        agregar_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_estudianteActionPerformed(evt);
            }
        });

        aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aulaActionPerformed(evt);
            }
        });

        numAlumnos.setBackground(new java.awt.Color(153, 153, 153));

        mausqueHerramienta.setEditable(false);
        mausqueHerramienta.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(21, 21, 21)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(agregar_estudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(grado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mausqueHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mausqueHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(agregar_estudiante)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradoActionPerformed

    private void agregar_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_estudianteActionPerformed

        try {
            int valor = aula.getSelectedIndex();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/escuela", "root", "Ivansito07615.");
            PreparedStatement pst = cn.prepareStatement("update aula set numAlumnos = ? where IDAula = " + valor);

            //tomo la cantidad actual
            int i = Integer.parseInt(numAlumnos.getText());

            //Tomo la cantidad a sumar
            int m = Integer.parseInt(mausqueHerramienta.getText());

           
            int contador2 = Integer.parseInt(num);
            if(contador2<=19){
                
            int c = i + m;
            pst.setInt(1, c);
            pst.executeUpdate();    
            }
            
            int opcion = grado.getSelectedIndex();
            int opcion2 = seccion.getSelectedIndex();
            int opcion3 = rol.getSelectedIndex();
            int opcion4 = aula.getSelectedIndex();

            //Ingresar Datos en la tabla factura compras
            
            int contador = Integer.parseInt(num);
            if (contador <=19) {

                try {
                    PreparedStatement pst2 = cn.prepareStatement("insert into alumno values(?,?,?,?,?,?,?,?,?,?)");
                    pst2.setString(1, null);

                    pst2.setString(2, nombre.getText());
                    pst2.setString(3, apellido.getText());
                    pst2.setString(4, direccion.getText());
                    pst2.setString(5, telefono.getText());
                    pst2.setString(6, matricula.getText());

                    //Con esto mandamos el codigo de la opcion que seleccionamos con el combobox
                    pst2.setString(7, String.valueOf(opcion));
                    pst2.setString(8, String.valueOf(opcion2));
                    pst2.setString(9, String.valueOf(opcion3));
                    pst2.setString(10, String.valueOf(opcion4));
                    pst2.executeUpdate();

                    //este bloque de código sirve para limpiar los campos de texto 
                    nombre.setText("");
                    apellido.setText("");
                    direccion.setText("");
                    telefono.setText("");
                    matricula.setText("");
                    JOptionPane.showMessageDialog(null, "Alumno agregado correctamente");

                } catch (HeadlessException | NumberFormatException | SQLException E) {
                    System.out.println(E);

                }
            } else {
                JOptionPane.showMessageDialog(null, "aula llena, debe crear una nueva aula");
            }

        } catch (HeadlessException | NumberFormatException | SQLException E) {
            System.out.println(E);

        }
    }//GEN-LAST:event_agregar_estudianteActionPerformed

    private void aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aulaActionPerformed
        try {
            int opcion = aula.getSelectedIndex();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/escuela", "root", "Ivansito07615.");
            PreparedStatement pst = cn.prepareStatement("select numAlumnos from aula where IDAula = ?");

            System.out.println(opcion);
            pst.setString(1, String.valueOf(opcion));
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                num = rs.getString("numAlumnos");

            }
            numAlumnos.setText(num);

        } catch (NullPointerException | SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_aulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_estudiante;
    private javax.swing.JTextField apellido;
    private javax.swing.JComboBox<String> aula;
    private javax.swing.JTextField direccion;
    private javax.swing.JComboBox<String> grado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField mausqueHerramienta;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel numAlumnos;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JComboBox<String> seccion;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
